from __future__ import annotations

SEOUL_TOP120_PLACES: list[dict[str, str]] = [
    {
        'CATEGORY': '관광특구',
        'AREA_CD': 'POI001',
        'AREA_NM': '강남 MICE 관광특구',
        'ENG_NM': 'Gangnam MICE Special Tourist Zone',
        'LAT': '37.513',
        'LNG': '127.0597',
    },
    {
        'CATEGORY': '관광특구',
        'AREA_CD': 'POI002',
        'AREA_NM': '동대문 관광특구',
        'ENG_NM': 'Dongdaemun Fashion Town Special Tourist Zone',
        'LAT': '37.5663',
        'LNG': '127.0092',
    },
    {
        'CATEGORY': '관광특구',
        'AREA_CD': 'POI003',
        'AREA_NM': '명동 관광특구',
        'ENG_NM': 'Myeong-dong Namdaemun Bukchang-dong Da-dong Mugyo-dong Special Tourist Zone',
        'LAT': '37.5636',
        'LNG': '126.985',
    },
    {
        'CATEGORY': '관광특구',
        'AREA_CD': 'POI004',
        'AREA_NM': '이태원 관광특구',
        'ENG_NM': 'Itaewon Special Tourist Zone',
        'LAT': '37.5345',
        'LNG': '126.9946',
    },
    {
        'CATEGORY': '관광특구',
        'AREA_CD': 'POI005',
        'AREA_NM': '잠실 관광특구',
        'ENG_NM': 'Jamsil Special Tourist Zone',
        'LAT': '37.5113',
        'LNG': '127.098',
    },
    {
        'CATEGORY': '관광특구',
        'AREA_CD': 'POI006',
        'AREA_NM': '종로·청계 관광특구',
        'ENG_NM': 'Jongno Cheonggye Special Toruist Zone',
        'LAT': '37.57',
        'LNG': '126.983',
    },
    {
        'CATEGORY': '관광특구',
        'AREA_CD': 'POI007',
        'AREA_NM': '홍대 관광특구',
        'ENG_NM': 'HongDae Culture & Arts Special Tourist Zone',
        'LAT': '37.5563',
        'LNG': '126.922',
    },
    {
        'CATEGORY': '고궁·문화유산',
        'AREA_CD': 'POI008',
        'AREA_NM': '경복궁',
        'ENG_NM': 'Gyeongbokgung Palace',
        'LAT': '37.5796',
        'LNG': '126.977',
    },
    {
        'CATEGORY': '고궁·문화유산',
        'AREA_CD': 'POI009',
        'AREA_NM': '광화문·덕수궁',
        'ENG_NM': 'Gwanghwamun & Deoksugung Palace',
        'LAT': '37.572',
        'LNG': '126.9757',
    },
    {
        'CATEGORY': '고궁·문화유산',
        'AREA_CD': 'POI010',
        'AREA_NM': '보신각',
        'ENG_NM': 'Bosingak',
        'LAT': '37.57',
        'LNG': '126.9835',
    },
    {
        'CATEGORY': '고궁·문화유산',
        'AREA_CD': 'POI011',
        'AREA_NM': '서울 암사동 유적',
        'ENG_NM': 'Amsa Prehistoric Settlement Site',
        'LAT': '37.5516',
        'LNG': '127.13',
    },
    {
        'CATEGORY': '고궁·문화유산',
        'AREA_CD': 'POI012',
        'AREA_NM': '창덕궁·종묘',
        'ENG_NM': 'Changdeokgung Palace & Jongmyo Shrine',
        'LAT': '37.5794',
        'LNG': '126.991',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI013',
        'AREA_NM': '가산디지털단지역',
        'ENG_NM': 'Gasan Digital Complex station',
        'LAT': '37.4816',
        'LNG': '126.8827',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI014',
        'AREA_NM': '강남역',
        'ENG_NM': 'Gangnam station',
        'LAT': '37.4979',
        'LNG': '127.0276',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI015',
        'AREA_NM': '건대입구역',
        'ENG_NM': 'Konkuk University station',
        'LAT': '37.5402',
        'LNG': '127.0697',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI016',
        'AREA_NM': '고덕역',
        'ENG_NM': 'Godeok station',
        'LAT': '37.5533',
        'LNG': '127.1542',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI017',
        'AREA_NM': '고속터미널역',
        'ENG_NM': 'Express Bus Terminal station',
        'LAT': '37.5049',
        'LNG': '127.0049',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI018',
        'AREA_NM': '교대역',
        'ENG_NM': 'Seoul National University of Education station',
        'LAT': '37.4936',
        'LNG': '127.0145',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI019',
        'AREA_NM': '구로디지털단지역',
        'ENG_NM': 'Guro Digital Complex station',
        'LAT': '37.4851',
        'LNG': '126.9016',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI020',
        'AREA_NM': '구로역',
        'ENG_NM': 'Guro station',
        'LAT': '37.503',
        'LNG': '126.8818',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI021',
        'AREA_NM': '군자역',
        'ENG_NM': 'Gunja station',
        'LAT': '37.5572',
        'LNG': '127.0797',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI023',
        'AREA_NM': '대림역',
        'ENG_NM': 'Daerim station',
        'LAT': '37.4932',
        'LNG': '126.8978',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI024',
        'AREA_NM': '동대문역',
        'ENG_NM': 'Dongdaemun station',
        'LAT': '37.5712',
        'LNG': '127.0095',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI025',
        'AREA_NM': '뚝섬역',
        'ENG_NM': 'Ttukseom station',
        'LAT': '37.5472',
        'LNG': '127.0474',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI026',
        'AREA_NM': '미아사거리역',
        'ENG_NM': 'Miasageori station',
        'LAT': '37.6133',
        'LNG': '127.0302',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI027',
        'AREA_NM': '발산역',
        'ENG_NM': 'Balsan station',
        'LAT': '37.5586',
        'LNG': '126.8397',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI029',
        'AREA_NM': '사당역',
        'ENG_NM': 'Sadang station',
        'LAT': '37.4766',
        'LNG': '126.9816',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI030',
        'AREA_NM': '삼각지역',
        'ENG_NM': 'Samgakji station',
        'LAT': '37.5349',
        'LNG': '126.9727',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI031',
        'AREA_NM': '서울대입구역',
        'ENG_NM': 'Seoul National University station',
        'LAT': '37.4812',
        'LNG': '126.9527',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI032',
        'AREA_NM': '서울식물원·마곡나루역',
        'ENG_NM': 'Seoul Botanic Park·Magongnaru station',
        'LAT': '37.567',
        'LNG': '126.8339',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI033',
        'AREA_NM': '서울역',
        'ENG_NM': 'Seoul station',
        'LAT': '37.5547',
        'LNG': '126.9707',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI034',
        'AREA_NM': '선릉역',
        'ENG_NM': 'Seolleung station',
        'LAT': '37.5046',
        'LNG': '127.0491',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI035',
        'AREA_NM': '성신여대입구역',
        'ENG_NM': "Sungshin Women's University station",
        'LAT': '37.5929',
        'LNG': '127.0165',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI036',
        'AREA_NM': '수유역',
        'ENG_NM': 'Suyu station',
        'LAT': '37.5929',
        'LNG': '127.0165',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI037',
        'AREA_NM': '신논현역·논현역',
        'ENG_NM': 'Sinnonhyeon·Nonhyeon station',
        'LAT': '37.5048',
        'LNG': '127.0253',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI038',
        'AREA_NM': '신도림역',
        'ENG_NM': 'Sindorim station',
        'LAT': '37.5089',
        'LNG': '126.8911',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI039',
        'AREA_NM': '신림역',
        'ENG_NM': 'Sillim station',
        'LAT': '37.4843',
        'LNG': '126.9298',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI040',
        'AREA_NM': '신촌·이대역',
        'ENG_NM': 'Sinchon·Ewha Womans University station',
        'LAT': '37.5593',
        'LNG': '126.9428',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI041',
        'AREA_NM': '양재역',
        'ENG_NM': 'Yangjae station',
        'LAT': '37.4842',
        'LNG': '127.0343',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI042',
        'AREA_NM': '역삼역',
        'ENG_NM': 'Yeoksam station',
        'LAT': '37.5007',
        'LNG': '127.0366',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI043',
        'AREA_NM': '연신내역',
        'ENG_NM': 'Yeonsinnae station',
        'LAT': '37.619',
        'LNG': '126.9209',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI044',
        'AREA_NM': '오목교역·목동운동장',
        'ENG_NM': 'Omokgyo·Mok-dong Stadium station',
        'LAT': '37.5243',
        'LNG': '126.8756',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI045',
        'AREA_NM': '왕십리역',
        'ENG_NM': 'Wangsimni station',
        'LAT': '37.5614',
        'LNG': '127.037',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI046',
        'AREA_NM': '용산역',
        'ENG_NM': 'Yongsan station',
        'LAT': '37.5299',
        'LNG': '126.9645',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI047',
        'AREA_NM': '이태원역',
        'ENG_NM': 'Itaewon station',
        'LAT': '37.5346',
        'LNG': '126.9946',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI048',
        'AREA_NM': '장지역',
        'ENG_NM': 'Jangji station',
        'LAT': '37.4783',
        'LNG': '127.1263',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI049',
        'AREA_NM': '장한평역',
        'ENG_NM': 'Janghanpyeong station',
        'LAT': '37.5611',
        'LNG': '127.0645',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI050',
        'AREA_NM': '천호역',
        'ENG_NM': 'Cheonho station',
        'LAT': '37.5389',
        'LNG': '127.1233',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI051',
        'AREA_NM': '총신대입구(이수)역',
        'ENG_NM': 'Chongshin University(Isu) station',
        'LAT': '37.4869',
        'LNG': '126.9817',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI052',
        'AREA_NM': '충정로역',
        'ENG_NM': 'Chungjeongno station',
        'LAT': '37.56',
        'LNG': '126.9634',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI053',
        'AREA_NM': '합정역',
        'ENG_NM': 'Hapjeong station',
        'LAT': '37.5495',
        'LNG': '126.9138',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI054',
        'AREA_NM': '혜화역',
        'ENG_NM': 'Hyehwa station',
        'LAT': '37.5822',
        'LNG': '127.0015',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI055',
        'AREA_NM': '홍대입구역(2호선)',
        'ENG_NM': 'Hongik University station(Line 2)',
        'LAT': '37.5571',
        'LNG': '126.9246',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI056',
        'AREA_NM': '회기역',
        'ENG_NM': 'Hoegi station',
        'LAT': '37.5895',
        'LNG': '127.0576',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI058',
        'AREA_NM': '가락시장',
        'ENG_NM': 'Garak Market',
        'LAT': '37.4942',
        'LNG': '127.1119',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI059',
        'AREA_NM': '가로수길',
        'ENG_NM': 'Garosu-gil',
        'LAT': '37.52',
        'LNG': '127.023',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI060',
        'AREA_NM': '광장(전통)시장',
        'ENG_NM': 'Gwangjang(Traditional) Market',
        'LAT': '37.57',
        'LNG': '127.0099',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI061',
        'AREA_NM': '김포공항',
        'ENG_NM': 'Gimpo Airport',
        'LAT': '37.5617',
        'LNG': '126.8017',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI063',
        'AREA_NM': '노량진',
        'ENG_NM': 'Noryangjin',
        'LAT': '37.5132',
        'LNG': '126.9411',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI064',
        'AREA_NM': '덕수궁길·정동길',
        'ENG_NM': 'Deoksugung-gil·Jeongdong-gil',
        'LAT': '37.5666',
        'LNG': '126.9732',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI066',
        'AREA_NM': '북촌한옥마을',
        'ENG_NM': 'Bukchon Hanok Village',
        'LAT': '37.5829',
        'LNG': '126.985',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI067',
        'AREA_NM': '서촌',
        'ENG_NM': 'Seochon',
        'LAT': '37.5795',
        'LNG': '126.9714',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI068',
        'AREA_NM': '성수카페거리',
        'ENG_NM': 'Seongsu Cafe Street',
        'LAT': '37.5446',
        'LNG': '127.0586',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI070',
        'AREA_NM': '쌍문역',
        'ENG_NM': 'Ssangmun-dong station',
        'LAT': '37.6487',
        'LNG': '127.0342',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI071',
        'AREA_NM': '압구정로데오거리',
        'ENG_NM': 'Apgujeong Rodeo Street',
        'LAT': '37.527',
        'LNG': '127.0404',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI072',
        'AREA_NM': '여의도',
        'ENG_NM': 'Yeouido',
        'LAT': '37.5215',
        'LNG': '126.9243',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI073',
        'AREA_NM': '연남동',
        'ENG_NM': 'Yeonnam-dong',
        'LAT': '37.5632',
        'LNG': '126.9232',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI074',
        'AREA_NM': '영등포 타임스퀘어',
        'ENG_NM': 'Yeongdeungpo Time square',
        'LAT': '37.517',
        'LNG': '126.9031',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI076',
        'AREA_NM': '용리단길',
        'ENG_NM': 'Yongnidan-gil',
        'LAT': '37.5312',
        'LNG': '126.965',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI077',
        'AREA_NM': '이태원 앤틱가구거리',
        'ENG_NM': 'Itaewon Antiques street',
        'LAT': '37.5345',
        'LNG': '126.996',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI078',
        'AREA_NM': '인사동',
        'ENG_NM': 'Insa-dong',
        'LAT': '37.5741',
        'LNG': '126.9855',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI079',
        'AREA_NM': '창동 신경제 중심지',
        'ENG_NM': 'Changdong New Economic Center',
        'LAT': '37.6536',
        'LNG': '127.0562',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI080',
        'AREA_NM': '청담동 명품거리',
        'ENG_NM': 'Cheongdam-dong Luxury Fashion street',
        'LAT': '37.5244',
        'LNG': '127.0473',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI081',
        'AREA_NM': '청량리 제기동 일대 전통시장',
        'ENG_NM': 'Traditional market in Cheongnyangni Jegi-dong',
        'LAT': '37.5804',
        'LNG': '127.0388',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI082',
        'AREA_NM': '해방촌·경리단길',
        'ENG_NM': 'Haebangchon·Gyeongnidan-gil',
        'LAT': '37.5405',
        'LNG': '126.9878',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI083',
        'AREA_NM': 'DDP(동대문디자인플라자)',
        'ENG_NM': 'DDP(Dongdaemun Design Plaza)',
        'LAT': '37.5671',
        'LNG': '127.0097',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI084',
        'AREA_NM': 'DMC(디지털미디어시티)',
        'ENG_NM': 'DMC(Digital Media City)',
        'LAT': '37.577',
        'LNG': '126.8887',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI085',
        'AREA_NM': '강서한강공원',
        'ENG_NM': 'Gangseo Hangang Park',
        'LAT': '37.5859',
        'LNG': '126.8188',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI086',
        'AREA_NM': '고척돔',
        'ENG_NM': 'Gocheok Dome',
        'LAT': '37.4982',
        'LNG': '126.8667',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI087',
        'AREA_NM': '광나루한강공원',
        'ENG_NM': 'Gwangnaru Hangang Park',
        'LAT': '37.5447',
        'LNG': '127.1204',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI088',
        'AREA_NM': '광화문광장',
        'ENG_NM': 'Gwanghwamun Square',
        'LAT': '37.5723',
        'LNG': '126.9769',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI089',
        'AREA_NM': '국립중앙박물관·용산가족공원',
        'ENG_NM': 'The National Museum of Korea·Yongsan Family Park',
        'LAT': '37.5238',
        'LNG': '126.9803',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI090',
        'AREA_NM': '난지한강공원',
        'ENG_NM': 'Nanji Hangang Park',
        'LAT': '37.5663',
        'LNG': '126.8734',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI091',
        'AREA_NM': '남산공원',
        'ENG_NM': 'Namsan Park',
        'LAT': '37.5512',
        'LNG': '126.9882',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI092',
        'AREA_NM': '노들섬',
        'ENG_NM': 'Nodeul island',
        'LAT': '37.517',
        'LNG': '126.9575',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI093',
        'AREA_NM': '뚝섬한강공원',
        'ENG_NM': 'Ttukseom Hangang Park',
        'LAT': '37.5312',
        'LNG': '127.0659',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI094',
        'AREA_NM': '망원한강공원',
        'ENG_NM': 'Mangwon Hangang Park',
        'LAT': '37.556',
        'LNG': '126.8952',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI095',
        'AREA_NM': '반포한강공원',
        'ENG_NM': 'Banpo Hangang Park',
        'LAT': '37.5095',
        'LNG': '126.9954',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI096',
        'AREA_NM': '북서울꿈의숲',
        'ENG_NM': 'Dream Forest',
        'LAT': '37.6208',
        'LNG': '127.0403',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI098',
        'AREA_NM': '서리풀공원·몽마르뜨공원',
        'ENG_NM': 'Seoripul Park·Montmartre Park',
        'LAT': '37.4877',
        'LNG': '126.9826',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI099',
        'AREA_NM': '서울광장',
        'ENG_NM': 'Seoul Plaza',
        'LAT': '37.5659',
        'LNG': '126.9778',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI100',
        'AREA_NM': '서울대공원',
        'ENG_NM': 'Seoul Grand Park',
        'LAT': '37.4284',
        'LNG': '127.0167',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI101',
        'AREA_NM': '서울숲공원',
        'ENG_NM': 'Seoul Forest',
        'LAT': '37.5443',
        'LNG': '127.0374',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI102',
        'AREA_NM': '아차산',
        'ENG_NM': 'Achasan',
        'LAT': '37.5716',
        'LNG': '127.1034',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI103',
        'AREA_NM': '양화한강공원',
        'ENG_NM': 'Yanghwa Hangang Park',
        'LAT': '37.5461',
        'LNG': '126.8988',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI104',
        'AREA_NM': '어린이대공원',
        'ENG_NM': "Children's Grand Park",
        'LAT': '37.5492',
        'LNG': '127.0792',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI105',
        'AREA_NM': '여의도한강공원',
        'ENG_NM': 'Yeouido Hangang Park',
        'LAT': '37.5492',
        'LNG': '127.0792',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI106',
        'AREA_NM': '월드컵공원',
        'ENG_NM': 'World Cup Park',
        'LAT': '37.5688',
        'LNG': '126.8851',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI107',
        'AREA_NM': '응봉산',
        'ENG_NM': 'Eungbongsan',
        'LAT': '37.5617',
        'LNG': '127.038',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI108',
        'AREA_NM': '이촌한강공원',
        'ENG_NM': 'Ichon Hangang Park',
        'LAT': '37.5166',
        'LNG': '126.9588',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI109',
        'AREA_NM': '잠실종합운동장',
        'ENG_NM': 'Jamsil (Seoul) Sports Complex',
        'LAT': '37.5151',
        'LNG': '127.0724',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI110',
        'AREA_NM': '잠실한강공원',
        'ENG_NM': 'Jamsil Hangang Park',
        'LAT': '37.5173',
        'LNG': '127.0815',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI111',
        'AREA_NM': '잠원한강공원',
        'ENG_NM': 'Jamwon Hangang Park',
        'LAT': '37.5115',
        'LNG': '127.0145',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI112',
        'AREA_NM': '청계산',
        'ENG_NM': 'Cheonggyesan',
        'LAT': '37.4388',
        'LNG': '127.056',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI113',
        'AREA_NM': '청와대',
        'ENG_NM': 'Cheongwadae',
        'LAT': '37.5868',
        'LNG': '126.9748',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI114',
        'AREA_NM': '북창동 먹자골목',
        'ENG_NM': 'Bukchang-dong food alley',
        'LAT': '37.5601',
        'LNG': '126.9811',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI115',
        'AREA_NM': '남대문시장',
        'ENG_NM': 'Namdaemun Market',
        'LAT': '37.559',
        'LNG': '126.9728',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI116',
        'AREA_NM': '익선동',
        'ENG_NM': 'Ikseon-dong',
        'LAT': '37.5742',
        'LNG': '126.988',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI117',
        'AREA_NM': '신정네거리역',
        'ENG_NM': 'Shinjeongnegeori Station',
        'LAT': '37.5168',
        'LNG': '126.8655',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI118',
        'AREA_NM': '잠실새내역',
        'ENG_NM': 'Jamsil Saenae Station',
        'LAT': '37.5111',
        'LNG': '127.0862',
    },
    {
        'CATEGORY': '인구밀집지역',
        'AREA_CD': 'POI119',
        'AREA_NM': '잠실역',
        'ENG_NM': 'Jamsil Station',
        'LAT': '37.5133',
        'LNG': '127.1002',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI120',
        'AREA_NM': '잠실롯데타워 일대',
        'ENG_NM': 'Jamsil Lotte Tower area',
        'LAT': '37.5126',
        'LNG': '127.1025',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI121',
        'AREA_NM': '송리단길·호수단길',
        'ENG_NM': 'Songridan-gil·Hosudan-gil',
        'LAT': '37.5145',
        'LNG': '127.106',
    },
    {
        'CATEGORY': '발달상권',
        'AREA_CD': 'POI122',
        'AREA_NM': '신촌 스타광장',
        'ENG_NM': 'Shinchon Star Plaza',
        'LAT': '37.559',
        'LNG': '126.9377',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI123',
        'AREA_NM': '보라매공원',
        'ENG_NM': 'Boramae Park',
        'LAT': '37.4934',
        'LNG': '126.9188',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI124',
        'AREA_NM': '서대문독립공원',
        'ENG_NM': 'Seodaemun Independence Park',
        'LAT': '37.5725',
        'LNG': '126.9575',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI125',
        'AREA_NM': '안양천',
        'ENG_NM': 'Anyangcheon River',
        'LAT': '37.5178',
        'LNG': '126.8676',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI126',
        'AREA_NM': '여의서로',
        'ENG_NM': 'Yeouiseoro',
        'LAT': '37.5237',
        'LNG': '126.9176',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI127',
        'AREA_NM': '올림픽공원',
        'ENG_NM': 'Olympic Park',
        'LAT': '37.521',
        'LNG': '127.1212',
    },
    {
        'CATEGORY': '공원',
        'AREA_CD': 'POI128',
        'AREA_NM': '홍제폭포',
        'ENG_NM': 'Hongje Waterfall',
        'LAT': '37.5905',
        'LNG': '126.9423',
    },
]